### ISSUE TITLE
Linux - reports 'No Device' when Makibox powered & connected but port not permissioned

### ISSUE THREAD

**Issue by ghost** [Makible/5DPrint#5]
In Linux (tested on Ubuntu 12.04) when the printer is plugged in and powered up 5DPrint fails to connect to the serial port `/dev/ttyACM0`. This is due to a permission issue if the user is not logged in as root.
The permissions for the port are:
`crw-rw---- 1 root dialout 166, 0 Nov 14  2013 /dev/ttyACM0`
It would be useful if the application reported that the port was there but could not connect.
The fix was to add the user to the 'dialout' group.
### Update

Can confirm that this is an issue in Ubuntu (12.04), Debian (Wheezy) and Fedora (20 beta). Users will need to be added to the _dialout_ group if they are to use a Makibox. The [Fedora 3D printing feature](http://fedoraproject.org/wiki/Features/3D_Printing) also mentions this.

In Linux to add a user to the _dialout_ group run the following as root `usermod -a -G dialout <username>`

**Comment by elliottpolk** [comment]
Added note to README for this. Thanks for the info sir! :+1:
