### ISSUE TITLE
Infos missing in Readme.md 

### ISSUE THREAD

**Issue by MarcusWolschon** [Makible/5DPrint#6]
That's a very...short readme file, not explaining 
- what 5dprint is!!!,
- what 3d printer it is used for (Makibox HT+LT only or also other printers?),
- how to build it
- how to install and use it (what is required? Chrome? Go? How to install?)
- where the rest of the documentation is (supported g-codes? serial protocol documentation?)

**Comment by elliottpolk** [comment]
Updated. Thanks for this! :+1:
